//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanMayTinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class HoaDon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HoaDon()
        {
            this.SanPhams = new HashSet<SanPham>();
        }
    
        public string ID { get; set; }
        public string IDNguoiDung { get; set; }
        public string IDNhanVien { get; set; }
        public string IDTrangThai { get; set; }
        public string IDCoSo { get; set; }
        public string IDNguoiGiaoHang { get; set; }
        public Nullable<System.DateTime> NgayXuatHD { get; set; }
    
        public virtual CoSo CoSo { get; set; }
        public virtual NguoiDung NguoiDung { get; set; }
        public virtual NguoiGiaoHang NguoiGiaoHang { get; set; }
        public virtual NhanVien NhanVien { get; set; }
        public virtual TrangThaiHoaDon TrangThaiHoaDon { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
    }
}
