//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebBanMayTinh
{
    using System;
    using System.Collections.Generic;
    
    public partial class SanPham
    {
        public string ID { get; set; }
        public string IDLoaiSanPham { get; set; }
        public string SoSeri { get; set; }
        public string IDCoSo { get; set; }
        public string IDTrangThai { get; set; }
        public string IDHoaDon { get; set; }
    
        public virtual CoSo CoSo { get; set; }
        public virtual HoaDon HoaDon { get; set; }
        public virtual LoaiSanPham LoaiSanPham { get; set; }
        public virtual TrangThaiSP TrangThaiSP { get; set; }
    }
}
